;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Abilities.Dash",DevComment="")
+GameplayTagList=(Tag="Abilities.Dash.OnCooldown",DevComment="")
+GameplayTagList=(Tag="Abilities.Poison",DevComment="")
+GameplayTagList=(Tag="Abilities.Warpstrike.ArrivedAtPoint",DevComment="")
+GameplayTagList=(Tag="Abilities.Warpstrike.NotifyThrow",DevComment="")
+GameplayTagList=(Tag="Abilities.Warpstrike.PreThrowEffects",DevComment="")
+GameplayTagList=(Tag="Character.Health.BlockRegen",DevComment="")
+GameplayTagList=(Tag="Character.Health.Regen",DevComment="")
+GameplayTagList=(Tag="Character.Mana.BlockRegen",DevComment="")
+GameplayTagList=(Tag="Character.Mana.Regen",DevComment="")
+GameplayTagList=(Tag="Damage.Magnitude",DevComment="")
+GameplayTagList=(Tag="WarpStrike.Started",DevComment="")

